name: Deploy to Gaia

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Secrets
        env:
          METUBE_COOKIES_TXT: ${{ secrets.METUBE_COOKIES_TXT }}
        run: |
          chmod +x scripts/ensure_secret.sh
          # Generate versioned secret for MeTube Cookies
          echo "METUBE_COOKIES_SECRET_NAME=$(echo "$METUBE_COOKIES_TXT" | ./scripts/ensure_secret.sh apollo_metube_cookies)" >> $GITHUB_ENV

      - name: Deploy Stack
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          PLEX_CLAIM: ${{ secrets.PLEX_CLAIM }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh --skip-build "apollo-core" docker-compose.yml
