name: Deploy to Gaia

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy with start.sh
        env:
          # Required for Traefik Rules in docker-compose.yml
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          PLEX_CLAIM: ${{ secrets.PLEX_CLAIM }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh --skip-build "apollo-core" docker-compose.yml
